// ---------------------------------------------------------------------------
// Hook Installation CLI
// ---------------------------------------------------------------------------
// Installs CodeScope convention enforcement into the git pre-commit hook.
// Detects husky and integrates into husky chain; otherwise uses .git/hooks/
// with existing hook backup and chaining.
//
// Usage: npx codescope install-hooks
// ---------------------------------------------------------------------------

import {
  existsSync,
  readFileSync,
  writeFileSync,
  renameSync,
  mkdirSync,
  chmodSync,
} from "node:fs";
import { join } from "node:path";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface InstallResult {
  installed: boolean;
  method: "husky" | "git-hooks";
  backedUp: boolean;
  message: string;
}

// ---------------------------------------------------------------------------
// Shell wrapper script template (for .git/hooks/pre-commit)
// ---------------------------------------------------------------------------

const WRAPPER_SCRIPT = `#!/bin/sh
# CodeScope convention enforcement pre-commit hook
# Auto-generated by: npx codescope install-hooks
# Do not edit -- use 'npx codescope uninstall-hooks' to remove

# Run existing hook if it was preserved
if [ -f ".git/hooks/pre-commit.codescope-backup" ]; then
  .git/hooks/pre-commit.codescope-backup
  EXISTING_EXIT=$?
  if [ $EXISTING_EXIT -ne 0 ]; then
    exit $EXISTING_EXIT
  fi
fi

# Get staged files (Added, Copied, Modified only)
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

# Check if sg (ast-grep) is available
if ! command -v sg >/dev/null 2>&1; then
  if ! npx sg --version >/dev/null 2>&1; then
    echo "[CodeScope] ast-grep (sg) not found -- skipping convention check"
    exit 0
  fi
fi

# Run CodeScope convention enforcement
node "node_modules/codescope/dist/enforcement/pre-commit-check.mjs" $STAGED_FILES
`;

// ---------------------------------------------------------------------------
// Husky block template (appended to .husky/pre-commit)
// ---------------------------------------------------------------------------

const HUSKY_BLOCK = `
# codescope-enforcement-start
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM)
if [ -n "$STAGED_FILES" ]; then
  node "node_modules/codescope/dist/enforcement/pre-commit-check.mjs" $STAGED_FILES
fi
# codescope-enforcement-end
`;

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Install CodeScope convention enforcement into the pre-commit hook.
 *
 * Detects husky (.husky/ directory) and integrates into husky chain.
 * Otherwise uses .git/hooks/ with existing hook backup and chaining.
 *
 * @param projectRoot - Absolute path to the project root
 * @returns InstallResult describing what was done
 */
export function installPreCommitHook(projectRoot: string): InstallResult {
  const huskyDir = join(projectRoot, ".husky");

  if (existsSync(huskyDir)) {
    return installHusky(projectRoot, huskyDir);
  }

  return installGitHooks(projectRoot);
}

// ---------------------------------------------------------------------------
// Internal: Husky integration (D-02)
// ---------------------------------------------------------------------------

function installHusky(projectRoot: string, huskyDir: string): InstallResult {
  const huskyHookPath = join(huskyDir, "pre-commit");

  let existing = "";
  if (existsSync(huskyHookPath)) {
    existing = readFileSync(huskyHookPath, "utf-8");
  }

  // Idempotency: check if marker block already present
  if (existing.includes("# codescope-enforcement-start")) {
    return {
      installed: true,
      method: "husky",
      backedUp: false,
      message:
        "CodeScope enforcement already present in husky pre-commit hook.",
    };
  }

  // Build new content
  let content: string;
  if (existing.length > 0) {
    // Append to existing husky hook
    content = existing.trimEnd() + "\n" + HUSKY_BLOCK;
  } else {
    // Create new husky hook with shebang
    content = "#!/bin/sh\n" + HUSKY_BLOCK;
  }

  writeFileSync(huskyHookPath, content, { mode: 0o755 });
  chmodSync(huskyHookPath, 0o755);

  return {
    installed: true,
    method: "husky",
    backedUp: false,
    message: "CodeScope enforcement added to husky pre-commit hook.",
  };
}

// ---------------------------------------------------------------------------
// Internal: .git/hooks/ fallback (D-01)
// ---------------------------------------------------------------------------

function installGitHooks(projectRoot: string): InstallResult {
  const hooksDir = join(projectRoot, ".git", "hooks");
  const hookPath = join(hooksDir, "pre-commit");
  const backupPath = join(hooksDir, "pre-commit.codescope-backup");

  // Create hooks directory if needed
  if (!existsSync(hooksDir)) {
    mkdirSync(hooksDir, { recursive: true });
  }

  // Backup existing hook
  let backedUp = false;
  if (existsSync(hookPath)) {
    renameSync(hookPath, backupPath);
    backedUp = true;
  }

  // Write wrapper script
  writeFileSync(hookPath, WRAPPER_SCRIPT, { mode: 0o755 });
  chmodSync(hookPath, 0o755);

  const backupMsg = backedUp
    ? " Existing hook backed up to pre-commit.codescope-backup."
    : "";
  return {
    installed: true,
    method: "git-hooks",
    backedUp,
    message: `CodeScope enforcement hook installed.${backupMsg}`,
  };
}

// ---------------------------------------------------------------------------
// CLI entry point (guarded for testability)
// ---------------------------------------------------------------------------

const isMainModule =
  typeof process !== "undefined" &&
  process.argv[1] &&
  import.meta.url &&
  (process.argv[1] === new URL(import.meta.url).pathname ||
    process.argv[1].endsWith("install-hooks.js") ||
    process.argv[1].endsWith("install-hooks.mjs"));

if (isMainModule) {
  const projectRoot = process.cwd();
  const result = installPreCommitHook(projectRoot);
  console.log(result.message);
  process.exit(result.installed ? 0 : 1);
}
